### ISSUE TITLE
Styling page "Supported Measurement Units" has broken code box

### ISSUE THREAD

**Issue by ReallyNotARussianSpy** [NativeScript/docs-v7#1395]
### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[ ] Improvement of existing article
[ ] Missing documentation
[ ] New article needed

### Please, tell us more details
![image](https://user-images.githubusercontent.com/32486009/46757184-6f0c3880-cc97-11e8-9f74-3c0585f4546d.png)

**Comment by NickIliev** [comment]
@AdJesumPerMariam  Thanks for reporting this one!
Fixed via [https://github.com/NativeScript/docs/pull/1396](https://github.com/NativeScript/docs/pull/1396)

**Comment by ReallyNotARussianSpy** [comment]
Thanks, but just an FYI it still appears to be an issue. https://docs.nativescript.org/ui/styling

**Comment by NickIliev** [comment]
@AdJesumPerMariam the PR is still in the `master` branch of the docs repo and will go live pretty soon
